assets/translations/en.json
assets/translations/nl.json
lib/main.dart
lib/widgets/transactions_list.dart

https://github.com/peercoin/peercoin-flutter/issues/8

I18n defect

---

lib/main.dart
lib/screens/app_settings_screen.dart
lib/screens/new_wallet.dart
lib/screens/qrcodescanner.dart
lib/screens/setup.dart
lib/screens/setup_pin_code.dart
lib/screens/setup_save_seed.dart
lib/screens/transaction_details.dart
lib/screens/wallet_home.dart
lib/screens/wallet_list.dart
lib/tools/app_routes.dart
lib/widgets/app_drawer.dart
lib/widgets/send_tab.dart
lib/widgets/transactions_list.dart

maintainable routes

---

lib/screens/auth_jail.dart
lib/tools/auth.dart

fix edge case where app is jailed from cold start and code is entered correctly at second or later attempt

fix edge case

---

lib/main.dart

For now a language without its region is supported

countrycode is optional

---

assets/translations/de.json

After installing the apk and swiping through the screens on my phone I found two little bugs

fix minor bugs in de.json

---

assets/translations/ru.json

Word "подключеннно" to "подключено"

Word correction

---

lib/widgets/receive_tab.dart
lib/widgets/transactions_list.dart
pubspec.yaml

- fix visual glitches on tablets

visual glitches on tablets

---

lib/providers/activewallets.dart
lib/screens/addressbook.dart
pubspec.yaml

- don't count sending addresses for address derivation

don't count sendaddresses for address derivation

---

lib/screens/about.dart
lib/screens/addressbook.dart
lib/screens/wallet_home.dart
lib/tools/app_themes.dart

Updated to be a little spicier

Updated transaction icons

---

assets/translations/de.json
assets/translations/en.json
lib/screens/app_settings_screen.dart
lib/screens/setup_save_seed.dart
lib/screens/transaction_details.dart
lib/widgets/double_tab_to_clipboard.dart
lib/widgets/receive_tab.dart
lib/widgets/wallet_home_qr.dart
pubspec.yaml

-  double tap on selectable text copies to clipboard 
-  version bump

 double tap on selectable text copies to clipboard 

---

lib/tools/app_localizations.dart

Fix bug with incorrect path to Norwegian Bokmål

Fix bug with incorrect path to Norwegian Bokmål

---

CHANGELOG.md
lib/tools/app_localizations.dart

Add Hausa and Swahili

---

lib/tools/app_localizations.dart

English should be on top or at E

English should be on top or at E

---

CHANGELOG.md
lib/tools/app_localizations.dart

Add language: Danish

---

lib/screens/wallet/wallet_list.dart

Remove us in iOS link

---

lib/tools/app_localizations.dart

Add Punjabi (pa)

---

assets/translations/en.json

Translation fix

---

assets/translations/en.json
lib/tools/price_ticker.dart

Remove Croatian kuna (HRK)

---

assets/translations/en.json

Remove unused string in en.json

Remove unused string in en.json

---

CHANGELOG.md

chore: Update version number to 1.2.8 in pubspec.yaml

---

BUILD.md
web/index.html
web/manifest.json

Browser extension build

---

lib/main.dart
lib/models/hive/adapters/base_writable_adapter.dart
lib/models/hive/adapters/ec_private_key_hive_adapter.dart
lib/models/hive/adapters/ec_public_key_hive_adapter.dart
lib/models/hive/app_options.dart
lib/models/hive/coin_wallet.dart
lib/models/hive/pending_notifications.dart
lib/models/hive/server.dart
lib/models/hive/wallet_address.dart
lib/models/hive/wallet_transaction.dart
lib/models/hive/wallet_utxo.dart
lib/providers/app_settings_provider.dart
lib/providers/encrypted_box_provider.dart
lib/providers/server_provider.dart
lib/providers/wallet_provider.dart
lib/tools/background_sync.dart
pubspec.lock
pubspec.yaml
test/transaction_building_test.dart

Refactor Hive imports to use hive_ce package

---

lib/widgets/wallet/roast_group/tabs/request_dkg_tab.dart

fixes https://github.com/peercoin/peercoin_flutter/issues/292

Update threshold parameter to use input from threshold controller

---

.vscode/mcp.json
CHANGELOG.md
android/app/build.gradle
android/app/proguard-rules.pro
android/gradle.properties
assets/translations/da.json
assets/translations/en.json
assets/translations/es.json
assets/translations/is.json
assets/translations/nb_NO.json
assets/translations/sv.json
lib/screens/wallet/roast/roast_wallet_add_participant.dart
lib/widgets/wallet/roast_group/setup_participants.dart
lib/widgets/wallet/roast_group/setup_participants_share_pubkey_bottom_sheet.dart
pubspec.lock
pubspec.yaml

closes https://github.com/peercoin/peercoin_flutter/issues/286

Improvements for setup participants bottom sheet
